/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as AiEmployeesIndexRouteImport } from './routes/ai-employees.index'
import { Route as SupportTicketIdRouteImport } from './routes/support.$ticketId'
import { Route as SitesSiteIdRouteImport } from './routes/sites.$siteId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as GrowAdminRouteImport } from './routes/grow.admin'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AiEmployeesAgentIdRouteImport } from './routes/ai-employees.$agentId'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files/$'
import { Route as ApiPublicInstagramWebhookRouteImport } from './routes/api/public/instagram/webhook'
import { Route as ApiPublicInstagramMediaSplatRouteImport } from './routes/api/public/instagram-media/$'
import { Route as ApiPublicDodoWebhookRouteImport } from './routes/api/public/dodo/webhook'
import { Route as ApiPublicAuthGoogleClientIdRouteImport } from './routes/api/public/auth.google-client-id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const AiEmployeesIndexRoute = AiEmployeesIndexRouteImport.update({
  id: '/ai-employees/',
  path: '/ai-employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportTicketIdRoute = SupportTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => SupportRoute,
} as any)
const SitesSiteIdRoute = SitesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => SitesRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowAdminRoute = GrowAdminRouteImport.update({
  id: '/grow/admin',
  path: '/grow/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AiEmployeesAgentIdRoute = AiEmployeesAgentIdRouteImport.update({
  id: '/ai-employees/$agentId',
  path: '/ai-employees/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInstagramWebhookRoute =
  ApiPublicInstagramWebhookRouteImport.update({
    id: '/api/public/instagram/webhook',
    path: '/api/public/instagram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInstagramMediaSplatRoute =
  ApiPublicInstagramMediaSplatRouteImport.update({
    id: '/api/public/instagram-media/$',
    path: '/api/public/instagram-media/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDodoWebhookRoute = ApiPublicDodoWebhookRouteImport.update({
  id: '/api/public/dodo/webhook',
  path: '/api/public/dodo/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthGoogleClientIdRoute =
  ApiPublicAuthGoogleClientIdRouteImport.update({
    id: '/api/public/auth/google-client-id',
    path: '/api/public/auth/google-client-id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/sites': typeof SitesRouteWithChildren
  '/solutions': typeof SolutionsRoute
  '/support': typeof SupportRouteWithChildren
  '/terms': typeof TermsRoute
  '/ai-employees/$agentId': typeof AiEmployeesAgentIdRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/grow/admin': typeof GrowAdminRoute
  '/invite/$token': typeof InviteTokenRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/ai-employees/': typeof AiEmployeesIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/public/auth/google-client-id': typeof ApiPublicAuthGoogleClientIdRoute
  '/api/public/dodo/webhook': typeof ApiPublicDodoWebhookRoute
  '/api/public/instagram-media/$': typeof ApiPublicInstagramMediaSplatRoute
  '/api/public/instagram/webhook': typeof ApiPublicInstagramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/sites': typeof SitesRouteWithChildren
  '/solutions': typeof SolutionsRoute
  '/support': typeof SupportRouteWithChildren
  '/terms': typeof TermsRoute
  '/ai-employees/$agentId': typeof AiEmployeesAgentIdRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/grow/admin': typeof GrowAdminRoute
  '/invite/$token': typeof InviteTokenRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/ai-employees': typeof AiEmployeesIndexRoute
  '/chat': typeof ChatIndexRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/public/auth/google-client-id': typeof ApiPublicAuthGoogleClientIdRoute
  '/api/public/dodo/webhook': typeof ApiPublicDodoWebhookRoute
  '/api/public/instagram-media/$': typeof ApiPublicInstagramMediaSplatRoute
  '/api/public/instagram/webhook': typeof ApiPublicInstagramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/sites': typeof SitesRouteWithChildren
  '/solutions': typeof SolutionsRoute
  '/support': typeof SupportRouteWithChildren
  '/terms': typeof TermsRoute
  '/ai-employees/$agentId': typeof AiEmployeesAgentIdRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/grow/admin': typeof GrowAdminRoute
  '/invite/$token': typeof InviteTokenRoute
  '/sites/$siteId': typeof SitesSiteIdRoute
  '/support/$ticketId': typeof SupportTicketIdRoute
  '/ai-employees/': typeof AiEmployeesIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/public/auth/google-client-id': typeof ApiPublicAuthGoogleClientIdRoute
  '/api/public/dodo/webhook': typeof ApiPublicDodoWebhookRoute
  '/api/public/instagram-media/$': typeof ApiPublicInstagramMediaSplatRoute
  '/api/public/instagram/webhook': typeof ApiPublicInstagramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/billing'
    | '/chat'
    | '/dashboard'
    | '/integrations'
    | '/knowledge'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/sites'
    | '/solutions'
    | '/support'
    | '/terms'
    | '/ai-employees/$agentId'
    | '/api/chat'
    | '/chat/$threadId'
    | '/grow/admin'
    | '/invite/$token'
    | '/sites/$siteId'
    | '/support/$ticketId'
    | '/ai-employees/'
    | '/chat/'
    | '/api/files/$'
    | '/api/public/auth/google-client-id'
    | '/api/public/dodo/webhook'
    | '/api/public/instagram-media/$'
    | '/api/public/instagram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/billing'
    | '/dashboard'
    | '/integrations'
    | '/knowledge'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/sites'
    | '/solutions'
    | '/support'
    | '/terms'
    | '/ai-employees/$agentId'
    | '/api/chat'
    | '/chat/$threadId'
    | '/grow/admin'
    | '/invite/$token'
    | '/sites/$siteId'
    | '/support/$ticketId'
    | '/ai-employees'
    | '/chat'
    | '/api/files/$'
    | '/api/public/auth/google-client-id'
    | '/api/public/dodo/webhook'
    | '/api/public/instagram-media/$'
    | '/api/public/instagram/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/billing'
    | '/chat'
    | '/dashboard'
    | '/integrations'
    | '/knowledge'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/sites'
    | '/solutions'
    | '/support'
    | '/terms'
    | '/ai-employees/$agentId'
    | '/api/chat'
    | '/chat/$threadId'
    | '/grow/admin'
    | '/invite/$token'
    | '/sites/$siteId'
    | '/support/$ticketId'
    | '/ai-employees/'
    | '/chat/'
    | '/api/files/$'
    | '/api/public/auth/google-client-id'
    | '/api/public/dodo/webhook'
    | '/api/public/instagram-media/$'
    | '/api/public/instagram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  ChatRoute: typeof ChatRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  IntegrationsRoute: typeof IntegrationsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResourcesRoute: typeof ResourcesRoute
  SitesRoute: typeof SitesRouteWithChildren
  SolutionsRoute: typeof SolutionsRoute
  SupportRoute: typeof SupportRouteWithChildren
  TermsRoute: typeof TermsRoute
  AiEmployeesAgentIdRoute: typeof AiEmployeesAgentIdRoute
  ApiChatRoute: typeof ApiChatRoute
  GrowAdminRoute: typeof GrowAdminRoute
  InviteTokenRoute: typeof InviteTokenRoute
  AiEmployeesIndexRoute: typeof AiEmployeesIndexRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
  ApiPublicAuthGoogleClientIdRoute: typeof ApiPublicAuthGoogleClientIdRoute
  ApiPublicDodoWebhookRoute: typeof ApiPublicDodoWebhookRoute
  ApiPublicInstagramMediaSplatRoute: typeof ApiPublicInstagramMediaSplatRoute
  ApiPublicInstagramWebhookRoute: typeof ApiPublicInstagramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/ai-employees/': {
      id: '/ai-employees/'
      path: '/ai-employees'
      fullPath: '/ai-employees/'
      preLoaderRoute: typeof AiEmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/$ticketId': {
      id: '/support/$ticketId'
      path: '/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof SupportTicketIdRouteImport
      parentRoute: typeof SupportRoute
    }
    '/sites/$siteId': {
      id: '/sites/$siteId'
      path: '/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof SitesSiteIdRouteImport
      parentRoute: typeof SitesRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grow/admin': {
      id: '/grow/admin'
      path: '/grow/admin'
      fullPath: '/grow/admin'
      preLoaderRoute: typeof GrowAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-employees/$agentId': {
      id: '/ai-employees/$agentId'
      path: '/ai-employees/$agentId'
      fullPath: '/ai-employees/$agentId'
      preLoaderRoute: typeof AiEmployeesAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram/webhook': {
      id: '/api/public/instagram/webhook'
      path: '/api/public/instagram/webhook'
      fullPath: '/api/public/instagram/webhook'
      preLoaderRoute: typeof ApiPublicInstagramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram-media/$': {
      id: '/api/public/instagram-media/$'
      path: '/api/public/instagram-media/$'
      fullPath: '/api/public/instagram-media/$'
      preLoaderRoute: typeof ApiPublicInstagramMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dodo/webhook': {
      id: '/api/public/dodo/webhook'
      path: '/api/public/dodo/webhook'
      fullPath: '/api/public/dodo/webhook'
      preLoaderRoute: typeof ApiPublicDodoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/google-client-id': {
      id: '/api/public/auth/google-client-id'
      path: '/api/public/auth/google-client-id'
      fullPath: '/api/public/auth/google-client-id'
      preLoaderRoute: typeof ApiPublicAuthGoogleClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SitesRouteChildren {
  SitesSiteIdRoute: typeof SitesSiteIdRoute
}

const SitesRouteChildren: SitesRouteChildren = {
  SitesSiteIdRoute: SitesSiteIdRoute,
}

const SitesRouteWithChildren = SitesRoute._addFileChildren(SitesRouteChildren)

interface SupportRouteChildren {
  SupportTicketIdRoute: typeof SupportTicketIdRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportTicketIdRoute: SupportTicketIdRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  ChatRoute: ChatRouteWithChildren,
  DashboardRoute: DashboardRoute,
  IntegrationsRoute: IntegrationsRoute,
  KnowledgeRoute: KnowledgeRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResourcesRoute: ResourcesRoute,
  SitesRoute: SitesRouteWithChildren,
  SolutionsRoute: SolutionsRoute,
  SupportRoute: SupportRouteWithChildren,
  TermsRoute: TermsRoute,
  AiEmployeesAgentIdRoute: AiEmployeesAgentIdRoute,
  ApiChatRoute: ApiChatRoute,
  GrowAdminRoute: GrowAdminRoute,
  InviteTokenRoute: InviteTokenRoute,
  AiEmployeesIndexRoute: AiEmployeesIndexRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
  ApiPublicAuthGoogleClientIdRoute: ApiPublicAuthGoogleClientIdRoute,
  ApiPublicDodoWebhookRoute: ApiPublicDodoWebhookRoute,
  ApiPublicInstagramMediaSplatRoute: ApiPublicInstagramMediaSplatRoute,
  ApiPublicInstagramWebhookRoute: ApiPublicInstagramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
