/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as AiEmployeesIndexRouteImport } from './routes/ai-employees.index'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AiEmployeesAgentIdRouteImport } from './routes/ai-employees.$agentId'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files/$'
import { Route as ApiPublicInstagramWebhookRouteImport } from './routes/api/public/instagram/webhook'
import { Route as ApiPublicDodoWebhookRouteImport } from './routes/api/public/dodo/webhook'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const AiEmployeesIndexRoute = AiEmployeesIndexRouteImport.update({
  id: '/ai-employees/',
  path: '/ai-employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AiEmployeesAgentIdRoute = AiEmployeesAgentIdRouteImport.update({
  id: '/ai-employees/$agentId',
  path: '/ai-employees/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInstagramWebhookRoute =
  ApiPublicInstagramWebhookRouteImport.update({
    id: '/api/public/instagram/webhook',
    path: '/api/public/instagram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDodoWebhookRoute = ApiPublicDodoWebhookRouteImport.update({
  id: '/api/public/dodo/webhook',
  path: '/api/public/dodo/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/ai-employees/$agentId': typeof AiEmployeesAgentIdRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/ai-employees/': typeof AiEmployeesIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/public/dodo/webhook': typeof ApiPublicDodoWebhookRoute
  '/api/public/instagram/webhook': typeof ApiPublicInstagramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/ai-employees/$agentId': typeof AiEmployeesAgentIdRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/ai-employees': typeof AiEmployeesIndexRoute
  '/chat': typeof ChatIndexRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/public/dodo/webhook': typeof ApiPublicDodoWebhookRoute
  '/api/public/instagram/webhook': typeof ApiPublicInstagramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/chat': typeof ChatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/ai-employees/$agentId': typeof AiEmployeesAgentIdRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/ai-employees/': typeof AiEmployeesIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/public/dodo/webhook': typeof ApiPublicDodoWebhookRoute
  '/api/public/instagram/webhook': typeof ApiPublicInstagramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/billing'
    | '/chat'
    | '/dashboard'
    | '/integrations'
    | '/pricing'
    | '/profile'
    | '/resources'
    | '/solutions'
    | '/ai-employees/$agentId'
    | '/api/chat'
    | '/chat/$threadId'
    | '/ai-employees/'
    | '/chat/'
    | '/api/files/$'
    | '/api/public/dodo/webhook'
    | '/api/public/instagram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/billing'
    | '/dashboard'
    | '/integrations'
    | '/pricing'
    | '/profile'
    | '/resources'
    | '/solutions'
    | '/ai-employees/$agentId'
    | '/api/chat'
    | '/chat/$threadId'
    | '/ai-employees'
    | '/chat'
    | '/api/files/$'
    | '/api/public/dodo/webhook'
    | '/api/public/instagram/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/billing'
    | '/chat'
    | '/dashboard'
    | '/integrations'
    | '/pricing'
    | '/profile'
    | '/resources'
    | '/solutions'
    | '/ai-employees/$agentId'
    | '/api/chat'
    | '/chat/$threadId'
    | '/ai-employees/'
    | '/chat/'
    | '/api/files/$'
    | '/api/public/dodo/webhook'
    | '/api/public/instagram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  ChatRoute: typeof ChatRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  IntegrationsRoute: typeof IntegrationsRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ResourcesRoute: typeof ResourcesRoute
  SolutionsRoute: typeof SolutionsRoute
  AiEmployeesAgentIdRoute: typeof AiEmployeesAgentIdRoute
  ApiChatRoute: typeof ApiChatRoute
  AiEmployeesIndexRoute: typeof AiEmployeesIndexRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
  ApiPublicDodoWebhookRoute: typeof ApiPublicDodoWebhookRoute
  ApiPublicInstagramWebhookRoute: typeof ApiPublicInstagramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/ai-employees/': {
      id: '/ai-employees/'
      path: '/ai-employees'
      fullPath: '/ai-employees/'
      preLoaderRoute: typeof AiEmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-employees/$agentId': {
      id: '/ai-employees/$agentId'
      path: '/ai-employees/$agentId'
      fullPath: '/ai-employees/$agentId'
      preLoaderRoute: typeof AiEmployeesAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram/webhook': {
      id: '/api/public/instagram/webhook'
      path: '/api/public/instagram/webhook'
      fullPath: '/api/public/instagram/webhook'
      preLoaderRoute: typeof ApiPublicInstagramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dodo/webhook': {
      id: '/api/public/dodo/webhook'
      path: '/api/public/dodo/webhook'
      fullPath: '/api/public/dodo/webhook'
      preLoaderRoute: typeof ApiPublicDodoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  ChatRoute: ChatRouteWithChildren,
  DashboardRoute: DashboardRoute,
  IntegrationsRoute: IntegrationsRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ResourcesRoute: ResourcesRoute,
  SolutionsRoute: SolutionsRoute,
  AiEmployeesAgentIdRoute: AiEmployeesAgentIdRoute,
  ApiChatRoute: ApiChatRoute,
  AiEmployeesIndexRoute: AiEmployeesIndexRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
  ApiPublicDodoWebhookRoute: ApiPublicDodoWebhookRoute,
  ApiPublicInstagramWebhookRoute: ApiPublicInstagramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
